version: '3.5'


services:
  db_auth:
    container_name: db_avito
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_DB=Avito
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.2-alpine
    restart: always




